version: 2

build:
   os: "ubuntu-22.04"
   tools:
      python: "3.8"
   jobs:
      pre_build:
      - pwd
      - cat brainscore_language/utils/document_plugins.py
      - cd brainscore_language/utils
      - pwd
      - python document_plugins.py


python:
   install:
      - requirements: docs/requirements.txt
